### ISSUE TITLE
Card Importer Archidekt Error

### ISSUE THREAD

**Issue by mustafakalash** [Amuzet/Tabletop-Simulator-Scripts#13]
Archidekt's card categories property is not guaranteed to have elements, leading to an index out of bounds on line 475 of the card importer.  Please add the following size check:
https://github.com/Amuzet/Tabletop-Simulator-Scripts/blob/master/Magic/Importer.lua#L475
```diff
-if('SideboardMaybeboard'):find(v.categories[1])then
+if #v.categories > 0 and ('SideboardMaybeboard'):find(v.categories[1]) then
```

**Comment by Amuzet** [comment]
Implemented
